# Server Configuration
server.port=8080
server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-exception=true


# msg91 configuration
msg91.authkey=438401AMdwnTdtm6784ec49P1
msg91.template_id=679e31fad6fc057bbf584c22
msg91.url.send=https://control.msg91.com/api/v5/otp
msg91.url.verify=https://control.msg91.com/api/v5/otp/verify
msg91.url.resend=https://control.msg91.com/api/v5/otp/retry
otp.demo-mode=false


# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
file.upload-dir=uploads/

# Database Configuration
#spring.datasource.url=jdbc:mysql://165.22.218.70:3306/vivah?serverTimezone=Asia/Kolkata
spring.datasource.url=jdbc:mysql://localhost:3306/maid_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&allowMultiQueries=true
spring.datasource.username=root
spring.datasource.password=Uttam@rku2005
#spring.datasource.password=Jaishrikrishna@001

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# OTP Configuration
otp.expiry.minutes=10
otp.length=4

# JWT Configuration (Base64 encoded)
jwt.secret=TXlTdXBlclNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbkluTWFpZFJlcG9zaXRvcnlBcHBsaWNhdGlvbjIwMjQ=

# Logging Configuration
logging.level.MaidRepository.maid=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Jackson Configuration
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-format=HH:mm:ss
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null